### ISSUE TITLE
whether Azure CLI ie required?

### ISSUE THREAD

**Issue by julianhu1979** [microsoft/PromptWizard#17]
2024-12-26,11:08:32.267 | azure.identity._internal.decorators | wrapper:
AzureCliCredential.get_token_info failed: Azure CLI not found on path
Traceback (most recent call last):
  File "/home/julian/.virtualenvs/promptwizard/lib/python3.12/site-packages/azure/identity/_internal/decorators.py", line 23, in wrapper
    token = fn(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/julian/.virtualenvs/promptwizard/lib/python3.12/site-packages/azure/identity/_credentials/azure_cli.py", line 125, in get_token_info
    return self._get_token_base(*scopes, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julian/.virtualenvs/promptwizard/lib/python3.12/site-packages/azure/identity/_credentials/azure_cli.py", line 147, in _get_token_base
    output = _run_command(command, self._process_timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julian/.virtualenvs/promptwizard/lib/python3.12/site-packages/azure/identity/_credentials/azure_cli.py", line 217, in _run_command
    raise CredentialUnavailableError(message=CLI_NOT_FOUND)

**Comment by raghav-2002-os** [comment]
Hi, could you please give more context as to how this error occurred?
Thanks

**Comment by julianhu1979** [comment]
doesn't matter, after i installed azure-cli in ubuntu, the issue resolved. so the project depends azure-cli, please add into readme
